name: Build and Publish Echelon-Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Echelon-Bot/Echelon-Bot/Echelon-Bot.csproj

      - name: Build
        run: dotnet build ./Echelon-Bot/Echelon-Bot/Echelon-Bot.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./Echelon-Bot/Echelon-Bot/Echelon-Bot.csproj --configuration Release --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: ./publish

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/echelon-bot:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/echelon-bot:latest
